# Basic Site Settings
title: "Fahimeh Orvati Nia"
name: "Fahimeh Orvati Nia"
description: "PhD Student | AI and Computer Vision Researcher"
url: "https://fahimehorvatinia.github.io"
repository: "fahimehorvatinia/fahimehorvatinia.github.io"

# Author Info
author:
  avatar: "profile.jpg"
  name: "Fahimeh Orvati Nia"
  bio: "PhD student in Computer Engineering at Texas A&M University, specializing in AI and computer vision."
  email: "fahimehorvatinia@gmail.com"
  location: "Texas A&M University, College Station, TX"
  linkedin: "https://linkedin.com/in/fahimehorvatinia"
  github: "fahimehorvatinia"
