# Basic Site Settings
locale                   : "en-US"
title                    : "Fahimeh Orvati Nia / About Me"
title_separator          : "-"
name                     : &name "Fahimeh Orvati Nia"
description              : &description "PhD in Computer Engineering @ Texas A&M University"
url                      : https://fahimehorvatinia.github.io # the base hostname & protocol for your site
baseurl                  : "" # leave blank unless the site is hosted in a subdirectory
repository               : "fahimehorvatinia/fahimehorvatinia.github.io" # update with your repository name

# Site Author
author:
  avatar           : "profile.png"
  name             : "Fahimeh Orvati Nia"
  pronouns         : "she/her"
  bio              : "Researcher in AI, machine learning, and computer vision with a focus on Plant Growth and Phenotyping"
  location         : "Texas A&M University, College Station, TX"
  employer         : "Texas A&M University"
  email            : "fahimehorvatinia@tamu.edu"

  # Academic websites
  googlescholar    : ""
  orcid            : ""
  pubmed           : ""
  researchgate     : ""
  scopus           : ""

  # Repositories and software development
  github           : "fahimehorvatinia"

  # Social media
  linkedin         : "https://linkedin.com/in/fahimehorvatinia"

# Site Settings
teaser                   : "default-teaser.png"
breadcrumbs              : true
words_per_minute         : 200
future                   : true
read_more                : "enabled"

# Atom Feed
atom_feed:
  hide                   : true

# SEO Related
google_site_verification : ""
bing_site_verification   : ""
alexa_site_verification  : ""
yandex_site_verification : ""

# Social Sharing
social:
  type                   : "Person"
  name                   : "Fahimeh Orvati Nia"
  links:
    - "https://linkedin.com/in/fahimehorvatinia"
    - "https://github.com/fahimehorvatinia"

# Analytics
analytics:
  provider               : false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true

# Collections
collections:
  teaching:
    output: false
  publications:
    output: false
  portfolio:
    output: false
  talks:
    output: false

# Defaults for Pages and Posts
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
